	<?php include("header.php"); ?>

	<section id="products">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<div class="row">
						<div class="col-md-12 col-sm-6 col-6">
							<div class="categories">
								<h4>Categories</h4>
								<ul class="categories_elem">
									<li>Man</li>
									<li>Women</li>
									<li>Childrens</li>
									<li>Hot Deals</li>
								</ul>
							</div>
						</div>

						<div class="col-md-12 col-sm-6 col-6">
							<div class="price_filter">
								<h4>Price Filter</h4>
								<div class="polzunok-container">
									<div class="polzunok"></div>
									<span class="polz_text">From
								    <input type="text" class="polzunok-input-left" />$</span>
								    <span class="polz_text">To
								    <input type="text" class="polzunok-input-right "/>$</span>
								</div>
							</div>
						</div>

						<div class="col-md-12 col-sm-6 col-6">
							<div class="sizes">
								<h4>Sizes</h4>
								<form class="sizes_form">
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="sizeS" name="size">
										<label for="sizeS">Small</label>
									</div>
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="sizeM" name="size">
										<label for="sizeM">Medium</label>
									</div>
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="sizeL" name="size">
										<label for="sizeL">Large</label>
									</div>
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="sizeX" name="size">
										<label for="sizeX">X Large</label>
									</div>
								</form>
							</div>
						</div>

						<div class="col-md-12 col-sm-6 col-6">
							<div class="sizes">
								<h4>Brands</h4>
								<form class="sizes_form">
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="Reebok" name="brand">
										<label for="Reebok">Reebok</label>
									</div>
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="Addidas" name="brand">
										<label for="Addidas">Addidas</label>
									</div>
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="Nike" name="brand">
										<label for="Nike">Nike</label>
									</div>
									<div class="line_size">
										<input class="checksquare" type="checkbox" id="Active" name="brand">
										<label for="Active">Active</label>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-9 products_images">
					<div class="row">
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product" width="90" height="100">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
							<div class="intend"></div>
						</div><!-- first line od products-->
						
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
							<div class="intend"></div>
						</div><!--second line of products-->

						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 col-12">
							<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
						</div><!-- third poducts line-->
						<div class="col-md-12">
							<div class="products_more">
								<a href="#">
									<span></span>
									<span></span>
									<span></span>
								</a>
							</div>
						</div>
					</div>
				</div><!--products_images-->
			</div>
		</div>
	</section>

	<section id="email">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="letter">
						<div class="letter_title">
							<h3>news letter</h3>
							<p>join us now to get all news and special offers</p>
						</div>
						<div class="form_for_email">
							<img src="img/mail.png" alt="mail">
							<form class="form_email">
								<input class="email_text" type="text" name="email" placeholder="type your email here">
								<input class="email_button" type="button" name="submit" value="join us">
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-sm-4 col-12">
					<div class="footer_logo">
						<img src="img/logo.png" alt="logo">
						<p>shopy c 2015 . your copy right here</p>
					</div>
				</div>

				<div class="col-lg-6 col-sm-7 col-12">
					<div class="footer_menu_wrap">
						<ul class="footer_menu">
							<div class="footer_menu_item">
								<li><a href="#">about us</a></li>
								<li><a href="#">contact us</a></li>
								<li><a href="#">support</a></li>
							</div>
							<div class="footer_menu_item">
								<li><a href="#">our feed</a></li>
								<li><a href="#">terms and conditions</a></li>
								<li><a href="#">our privacy</a></li>
							</div>
							<div class="footer_menu_item">
								<li><a href="#">join us</a></li>
								<li><a href="#">live support</a></li>
							</div>
						</ul>
					</div>
				</div>

				<div class="col-lg-2 col-sm-1 col-12">
					<div class="payment">
						<h5>Payment Methods</h5>
						<div class="payment_img">
							<img src="img/mastercard.svg" alt="mastercard">
							<img src="img/mastercard1.svg" alt="mastercard">
							<img src="img/paypal.svg" alt="mastercard">
							<img src="img/visa.svg" alt="mastercard">
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

		<script
  			src="https://code.jquery.com/jquery-3.3.1.js"
  			integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  			crossorigin="anonymous"></script>
  		<script type="text/javascript" src="js/polzunok.js"></script>
  		<script type="text/javascript" src="slick/slick.min.js"></script>
  		<script type="text/javascript" src="js/jquery-ui.min.js"></script>
  		<script type="text/javascript" src="js/jquery.ui.touch-punch.min.js"></script>
		<script src="js/script.js"></script>
	</body>
</html>