	<?php include("header.php"); ?>

	<section id="product_info">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 offset-lg-1 col-md-5 offset-md-0 col-12 product_images" >
					<div class="product_info_images">
						<div class="product_info_image">
								<img class="product_info_image_click" src="img/12.png">
								<img class="product_info_image_click" src="img/product.png">
								<img class="product_info_image_click" src="img/product3.png">
						</div>
						<div class="product_info_buttons">
							<div class="product_slide_img">
								<img src="img/12_min.png" alt="product">
							</div>
							<div class="product_slide_img">
								<img src="img/product.png" alt="product">		
								</div>
							<div class="product_slide_img">
								<img src="img/product3.png" alt="product">
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-6 offset-lg-1 col-md-7 offset-md-0 product_detail_info">
					<div class="product_detail_info">
						<div class="product_di_text">
							<h1>full winter kit</h1>
							<h5>Half Jacket + Skiny Trousers + Boot leather</h5>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit enim quae, vel beatae ex eos dolorum magnam nostrum hic, voluptates sint molestiae explicabo recusandae fuga. Quisquam ea obcaecati cupiditate in.</p>
						</div>
						<div class="product_di_nav">
							<div class="choose_options">
								<div class="choose_size">Choose Size: 
									<div class="size_btn_line">
										<span class="size_btn">S</span>
									</div>
									<div class="size_btn_line">
										- <span class="size_btn size_btn_active">M</span> -
									</div>
									<div class="size_btn_line"> 
										<span class="size_btn">L</span> -
									</div>
									<div class="size_btn_line">  
										<span class="size_btn">XL</span>
									</div>
								</div>
								<p class="choose_numder">
									Choose Quantity: <button id="plus">+</button> 
									<span id="counter">0</span> 
									<button id="minus">-</button>
								</p>
							</div>
							<div class="price_order">
								<span>Price : 120$</span>
								<div class="product_icons">
									<i class="fas fa-globe"></i>
									<i class="fas fa-cart-plus"></i>
									<i class="far fa-heart"></i>
									<button class="order-btn add_to_cart">Order Now</button>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 price_order1">
					<span>Price : 120$</span>
					<div class="product_icons">
						<i class="fas fa-globe"></i>
						<i class="fas fa-cart-plus"></i>
						<i class="far fa-heart"></i>
						<button class="order-btn add_to_cart">Order Now</button>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section id="products">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="products_title">
							<h2><span>related</span> products</h2>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
					</div>
				</div>
				<div class="col-md-12 products_images">
						<div class="row">
							<div class="col-md-3 col-sm-6 col-12">
								<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus add_to_cart"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
							</div>
							<div class="col-md-3 col-sm-6 col-12">
								<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus add_to_cart"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
							</div>
							<div class="col-md-3 col-sm-6 col-12">
								<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus add_to_cart"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
							</div>
							<div class="col-md-3 col-sm-6 col-12">
								<div class="product_image">
								<a href="product.phtml"><img src="img/product.png" alt="product"></a>
								<a href="product.phtml"><p>Reebok Track Jacket</p></a>
								<span class="product_image_price">100$</span>
								<div class="product_image_hover">
									<a href="product.phtml">
										<img src="img/product.png" alt="product">
										<p class="product_image_title">Reebok Track Jacket</p>
									</a>
									<p class="product_image_udertitle">sizes<span> : </span>s - m - l - xl</p>
									<div class="product_colors">
										<span class="red"></span>
										<span class="black"></span>
										<span class="blue"></span>
										<span class="green"></span>
									</div>
									<div class="product_icons">
										<i class="fas fa-globe"></i>
										<i class="fas fa-cart-plus add_to_cart"></i>
										<i class="far fa-heart"></i>
									</div>
								</div>
							</div>
							</div>
						</div>
				</div><!--products_images-->
			</div>
		</div>
	</section>

	<?php include("footer.php"); ?>